### ISSUE TITLE
NcISO is not computing the ISO fileIdentifier correctly from the id and naming_authority

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/threddsIso#10]
According to the [ACDD Mappings](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_%28ACDD%29_Mappings), the ISO 19115-2 `fileIdentifier` is supposed to be computed from the combination of the netcdf attributes `id` and `naming_authority`. 

Yet if we look at a [dataset where both `naming_authority` and `id` are specified](
http://oos.soest.hawaii.edu/thredds/catalog/hioos/roms_forec/hiog/catalog.html?dataset=roms_hiog_forecast/ROMS_Oahu_Regional_Ocean_Model_best.ncd), we find that currently this is not working:

While the [OPeNDAP Dataset Access Form](http://oos.soest.hawaii.edu/thredds/dodsC/hioos/roms_forec/hiog/ROMS_Oahu_Regional_Ocean_Model_best.ncd.html) specifies:
```
id: roms_hiog_forecast
naming_authority: org.pacioos
```
when we look at the [ISO record](http://oos.soest.hawaii.edu/thredds/iso/hioos/roms_forec/hiog/ROMS_Oahu_Regional_Ocean_Model_best.ncd?catalog=http%3A%2F%2Foos.soest.hawaii.edu%2Fthredds%2Fcatalog%2Fhioos%2Froms_forec%2Fhiog%2Fcatalog.html&dataset=roms_hiog_forecast%2FROMS_Oahu_Regional_Ocean_Model_best.ncd) we see
```
  <gmd:fileIdentifier>
      <gco:CharacterString>roms_hiog_forecast/ROMS_Oahu_Regional_Ocean_Model_best.ncd</gco:CharacterString>
   </gmd:fileIdentifier>
```
which is just the THREDDS path, with no naming authority information.

It looks like there are two problems with the [UnidataDD2MI.xsl](https://github.com/Unidata/threddsIso/blob/master/src/main/resources/xsl/nciso/UnidataDD2MI.xsl) file. 

1. The `id` first checks to see if there is a THREDDS ID, and then checks to see if there is a netcdf `id` attribute.   It should be the other way around, because there will always be THREDDS ID (the pathname), and therefore the netcdf `id`, if present, will never be used.  See https://github.com/Unidata/threddsIso/blob/master/src/main/resources/xsl/nciso/UnidataDD2MI.xsl#L31

1. The `fileIdentifier` is being constructed using the `id` only, without the `naming_authority` information.  See https://github.com/Unidata/threddsIso/blob/master/src/main/resources/xsl/nciso/UnidataDD2MI.xsl#L181

**Comment by rsignell-usgs** [comment]
@geoneubie, @kwilcox, @brianmckenna, @dpsnowden, @amilan17, @lukecampbell, @dblodgett-usgs, please review this issue and the proposed fix PR #12, as it will change the ISO `fileIdentifier` (and therefore the CSW `identifier`)  for all datasets on THREDDS.   

While it's obviously not desirable to have identifiers change, the existing system does not follow the [ACDD mapping](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_%28ACDD%29_Mappings) that is required to make the datasets identifiers unique:  including the `naming_authority`!   I think it's better to correct his now rather than continuing to generate identifiers that ignore the `id` and `naming_authority` in the datasets they are supposed to identify!

**Comment by kwilcox** [comment]
:+1: for selecting the global attribute 'id' over the THREDDS Metadata 'id' 
:+1: for prefixing said `id` with the global attribute `naming_authority`

Made a small comment on the PR

**Comment by dblodgett-usgs** [comment]
+1 to this solution. I'll let others evaluate the technical approach.

**Comment by amilan17** [comment]
@rsignell-usgs 
Thanks for creating this issue. I think this will be a useful improvement to the XSL. Note that it's been our practice to encode the combination of  naming authority and id with a colon. 
like so: 
<code>gov.noaa:fileID</code>

This will enable decoupling of the two variables programmatically if needed.
