### ISSUE TITLE
Compatibility with THREDDS 5.0.0

### ISSUE THREAD

**Issue by cwardgar** [Unidata/threddsIso#16]
threddsIso fails to compile against THREDDS 5.0.0-SNAPSHOT. The biggest issue is that 5.0.0 deprecated all the classes in `thredds.catalog` and moved them to `legacy.jar`. And unfortunately, simply adding that dependency to threddsIso doesn't come close to resolving all of the breakage. I attempted to fix the remaining issues myself, but bailed because I don't understand the catalog machinery and how it was changed well enough.

**Comment by lesserwhirls** [comment]
Thanks for jumping in on this @cwardgar! I think a lot of the catalog code can be removed using the thredds.server.dataset.TdsRequestedDataset in v5.0. I was going to take a look at this once I get wms back up and running.

For a little more info, see https://bugtracking.unidata.ucar.edu/browse/TDS-190

**Comment by cwardgar** [comment]
Cool, sounds like you have a handle on how to do it.

Note that threddsIso uses `NcMLWriter`, whose API changed in 5.0.0. That's actually the reason that I jumped into this. It's a pretty straightforward fix, but ping me if you have a question about it.

**Comment by lesserwhirls** [comment]
Ok, I started a branch that uses THREDDS v5, and it compiles and passes the tests included with threddsIso: [threddsIsoTds5 branch](/Unidata/threddsIso/tree/threddsIsoTds5)

The next step should be to update the deps to make sure they are in line with what THREDDS 5 uses. After that, we can hook up the new threddsIso to TDS 5 and see how things go. Hopefully smooth :-)

This does not address the circular dependency on tds. That will come later - let's just get this working for now.

**Comment by cwardgar** [comment]
Syncing the deps is best done with the `thredds-parent` BOM, which I added to the Gradle build for 4.6.4. Something like:
```xml
			<dependency>
				<groupId>edu.ucar</groupId>
				<artifactId>thredds-parent</artifactId>
				<version>${thredds.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```
Looks like we haven't published that BOM to Nexus yet though. A simple `./gradlew publish` should do the trick.

**Comment by lesserwhirls** [comment]
Do we have a BOM for thredds 5?

**Comment by cwardgar** [comment]
[Yep](https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/thredds-parent/5.0.0-SNAPSHOT/). Kinda old though. You should publish a new one.

**Comment by lesserwhirls** [comment]
Does it get published along with the other artifacts when using the publish
goal, or does it have to be done special?

**Comment by cwardgar** [comment]
It gets published along with everything else. There's also an individual task for it, but I don't remember it off the top of my head (do `./gradle tasks --all` is you're really, really curious).
