### ISSUE TITLE
UnidataDD2MI.xsl doesn't compile because of 111 errors

### ISSUE THREAD

**Issue by tjaensch** [Unidata/threddsIso#23]
I opened the file in Oxygen and it reports 111 errors, also the file doesn't compile as is...?

**Comment by amilan17** [comment]
Hi Thomas,
Did you try setting the transformation in engine in Oxygen to Saxon HE or
Saxon PE?


Anna
*~~~~~~Metadata Adds Meaning~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
(formerly NOAA’s National Geophysical Data Center)
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by tjaensch** [comment]
Thanks, that works. The transformation engine has to be set to Saxon HE or Saxon PE for the stylesheet to compile.
